# Install Orbit globally on Windows (PATH + config source_root).
# Called by `zig build setup`.

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
$Exe = Join-Path $Root "zig-out\bin\orbit.exe"

if (-not (Test-Path $Exe)) {
    Write-Error "orbit.exe not found at $Exe — run zig build first"
    exit 1
}

$ConfigDir = Join-Path $env:APPDATA "orbit"
New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null
Set-Content -Path (Join-Path $ConfigDir "source_root") -Value $Root -NoNewline
Add-Content -Path (Join-Path $ConfigDir "source_root") -Value "`n"

$LocalBin = Join-Path $env:LOCALAPPDATA "Orbit\bin"
New-Item -ItemType Directory -Force -Path $LocalBin | Out-Null

$Launcher = Join-Path $LocalBin "orbit.cmd"
@"
@echo off
REM Orbit launcher — generated by zig build setup
set "ORBIT_ROOT=$Root"
if exist "%ORBIT_ROOT%\zig-out\bin\orbit.exe" (
  if /I "%~1"=="help" goto :fg
  if /I "%~1"=="ide-setup" goto :fg
  if /I "%~1"=="--ide-setup" goto :fg
  if /I "%~1"=="-h" goto :fg
  if /I "%~1"=="--help" goto :fg
  if /I "%~1"=="-V" goto :fg
  if /I "%~1"=="--version" goto :fg
  start "" "%ORBIT_ROOT%\zig-out\bin\orbit.exe" %*
  echo Orbit terminal opened successfully
  exit /b 0
)
echo orbit.exe missing — rebuild with: cd /d "%ORBIT_ROOT%" ^&^& zig build
exit /b 1
:fg
"%ORBIT_ROOT%\zig-out\bin\orbit.exe" %*
exit /b %ERRORLEVEL%
"@ | Set-Content -Path $Launcher -Encoding ASCII

# Prepend LocalBin to user PATH if missing.
$userPath = [Environment]::GetEnvironmentVariable("Path", "User")
if ($null -eq $userPath) { $userPath = "" }
$parts = $userPath -split ";" | Where-Object { $_ -ne "" }
if ($parts -notcontains $LocalBin) {
    $newPath = if ($userPath.Trim().Length -eq 0) { $LocalBin } else { "$LocalBin;$userPath" }
    [Environment]::SetEnvironmentVariable("Path", $newPath, "User")
    Write-Host "Added to user PATH: $LocalBin"
    Write-Host "Open a new terminal for 'orbit' to be available."
} else {
    Write-Host "PATH already contains: $LocalBin"
}

Write-Host "Orbit setup complete."
Write-Host "  Config:  $ConfigDir"
Write-Host "  Launcher: $Launcher"
Write-Host "  Source:  $Root"
Write-Host ""
Write-Host "Try:  orbit --help"
Write-Host "      orbit"
Write-Host "  or: zig build run   (from the Orbit repo)"
